version: '3'

services:
  web:
    build: .
    ports:
     - "80:3001"
  mqtt:
    image: "eclipse-mosquitto"
    ports:
     - "1883:1883"
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    ports:
     - "8000:8000"

        