version: '3'

services:
  web:
    build: .
    volumes: 
     - ./:/usr/src/app/
    ports:
     - "80:3001"
  mqtt:
    image: "eclipse-mosquitto"
    ports:
     - "1883:1883"
  redis:
    image: "redis"

        