version: '3'

services:
  web:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
     - "80:3001"
    environment:
      MQTT_URL: ${MOSQUITTO_URL}
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD}
    command: [ "node", "dist/index.js"]
  mqtt:
    build:
      context: mosquitto
      dockerfile: Dockerfile
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
    ports:
      - 1883:1883
