version: '3'

services:
  web:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
     - "80:3001"
    environment:
      CLOUDMQTT_URL: ${CLOUDMQTT_URL}
    command: [ "node", "dist/index.js"]
  mqtt:
    hostname: mqtt
    build:
      context: mosquitto
      dockerfile: Dockerfile
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
    ports:
      - 1883:1883
  lanterniot:
    image: lanterniot
    build:
      context: LanternIoT
      dockerfile: Dockerfile
    environment:
      - NUMBER_OF_LAMPS=${NUMBER_OF_LAMPS}