version: '3'

services:
  web:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
     - "80:3001"
    depends_on:
      - "dynamodb"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DYNAMODB: "http://dynamodb:8000"
      MQTT_URL: "mqtt://mqtt:1883"
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD}
    command: [ "node", "dist/index.js"]
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    ports:
     - "8000:8000"
  mqtt:
    build:
      context: mosquitto
      dockerfile: Dockerfile
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
    ports:
      - 1883:1883