version: '3'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.api
    image: jameslinnegar/lantern_api
    depends_on:
        - postgres
        - mqtt
        - redis
    environment:
      CLOUDMQTT_URL: ${CLOUDMQTT_URL}
      REDIS_URL: ${REDIS_URL}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      DATABASE_URL: "postgres://user:pass@postgres:5432/db"
    command: ["./bin/wait-for-postgres.sh", "postgres", "./bin/server.sh"]
    ports:
      - "80:3001"
    networks:
      - lantern-network

  queue:
    build:
      context: api
      dockerfile: Dockerfile.queue
    image: jameslinnegar/lantern_queue
    depends_on:
        - postgres
        - mqtt
        - redis
    environment:
      CLOUDMQTT_URL: ${CLOUDMQTT_URL}
      REDIS_URL: ${REDIS_URL}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      DATABASE_URL: "postgres://user:pass@postgres:5432/db"
    command: ["./bin/wait-for-postgres.sh", "postgres", "./bin/queue.sh"]
    networks:
      - lantern-network
  mqtt:
    hostname: mqtt
    build:
      context: mosquitto
      dockerfile: Dockerfile
    image: eclipse-mosquitto
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
    ports:
      - 1883:1883
    networks:
      - lantern-network
  postgres:
    image: postgres:10.4
    networks:
      - lantern-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  redis:
    image: redis
    networks:
      - lantern-network    
    ports:
      - 6379:6379  
networks:
  lantern-network:
    driver: bridge # a user defined bridge is required; the default bridge network doesn't support name resolution
