version: '3'

services:
  web:
    build: .
    ports:
     - "8080:3001"
    environment:
     HOST: "${HOST}"
     CLIENT: "${CLIENT}"
  mqtt:
    image: "eclipse-mosquitto"
    ports:
     - "1883:1883"

        